export default Object.freeze({
  AADHAR_NUMBER_ENTER_SCREEN: 'AadharNumberEnterScreen',
  AADHAR_OTP_ENTER_SCREEN: 'AadharOtpEnterScreen',
  BANK_DETAILS_ENTER_SCREEN: 'BankDetailsEnterScreen',
  BANK_TRANSFER_AMOUNT_ENTER_SCREEN: 'BankTransferAmountEnterScreen',
  BANK_TRANSFER_REASON_SCREEN: 'BankTransferReasonScreen',
  BASIC_DETAILS_SCREEN: 'BasicDetailsScreen',
  BILLS_AND_BOOKING_SCREEN: 'BillsAndBookingScreen',
  BRODBAND_AMOUNT_ENTER_SCREEN: 'BrodbandAmountEnterScreen',
  BRODBAND_FORM_SCREEN: 'BrodbandFormScreen',
  BRODBAND_SERVICE_PROVIDER_SCREEN: 'BrodbandServiceProviderScreen',
  CIBIL_RESULT_SCREEN: 'CibilResultScreen',
  COLLEGE_DETAILS_SCREEN: 'CollegeDetailsScreen',
  CONTACTS_AND_LASTPAYMENTS_SCREEN: 'ContactsAndLastPaymentsScreen',
  CONTACTS_SCREEN: 'ContactsScreen',
  DPIN_SCREEN: 'DpinScreen',
  ELECTRICTY_BILL_AMOUNT_ENTER_SCREEN: 'ElectrictyBillAmountEnterScreen',
  ELECTRICTY_SERVICE_PROVIDER_SCREEN: 'ElectrictyServiceProviderScreen',
  ELECTRICTY_STATE_SELECT_SCREEN: 'ElectrictyStateSelectScreen',
  EMAIL_ENTER_SCREEN: 'EmailEnterScreen',
  EMAIL_OTP_ENTER_SCREEN: 'EmailOtpEnterScreen',
  EMI_BRANDS_SCREEN: 'EmiBrandsScreen',
  EMI_CONFIRM_SCREEN: 'EmiConfirmScreen',
  EMI_PLANS_SCREEN: 'EmiPlansScreen',
  FASTAG_AMOUNT_ENTER_SCREEN: 'FastagAmountEnterScreen',
  FASTAG_FORM_SCREEN: 'FastagFormScreen',
  FASTAG_SERVICE_PROVIDER_SCREEN: 'FastagServiceProviderScreen',
  GAS_BOOKING_SCREEN: 'GasBookingScreen',
  GAS_SERVICE_PROVIDER_SCREEN: 'GasServiceProviderScreen',
  GET_FRIEND_CONTACT_SCREEN: 'GetFriendContactScreen',
  HOME_SCREEN: 'HomeScreen',
  MOBILE_NUMBER_ENTER_SCREEN: 'MobileNumberEnterScreen',
  MOBLE_OTP_ENTER_SCREEN: 'MobileOtpEnterScreen',
  OFFERS_SCREEN: 'OffersScreen',
  PERMISSIONS_SCREEN: 'PermissionsScreen',
  POSTPAID_RECHARGE_BILL_SCREEN: 'PostpaidRechargeBillScreen',
  POSTPAID_RECHARGE_SERVICE_PROVIDER_SCREEN:
    'PostpaidRechargeServiceProviderScreen',
  PREPAID_RECHARGE_PLAN_FINAL_SCREEN: 'PrepaidRechargePlanFinalScreen',
  PREPAID_RECHARGE_PLAN_SELECT_SCREEN: 'PrepaidRechargePlanSelectScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  PROFILE_SETTINGS_SCREEN: 'ProfileSettingsScreen',
  SELFIE_SCREEN: 'SelfieScreen',
  SUCCESS_SCREEN: 'SuccessScreen',

  COLLEGE_DETAILS_SCREEN_NAVIGATION: 'CollegeDetailsScreenNavigation',
});
